-- Create the users table (handled by Supabase Auth)

-- Create the daily_entries table
CREATE TABLE public.daily_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  date date NOT NULL,
  mood text NOT NULL,
  journal_entry text,
  step_count integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT unique_user_date UNIQUE (user_id, date)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.daily_entries ENABLE ROW LEVEL SECURITY;

-- Create policies for daily_entries
CREATE POLICY "Users can insert their own daily entries"
ON public.daily_entries
FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own daily entries"
ON public.daily_entries
USING (auth.uid() = user_id);

USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own daily entries"
ON public.daily_entries
FOR DELETE
USING (auth.uid() = user_id);

-- Create a function to get the weekly summary
CREATE OR REPLACE FUNCTION get_weekly_summary(p_user_id uuid)
RETURNS TABLE(entry_date date, mood_score smallint, steps integer)
AS $$
BEGIN
  RETURN QUERY
  SELECT
    de.date,
    CASE de.mood
      WHEN 'Happy' THEN 5
      WHEN 'Good' THEN 4
      WHEN 'Okay' THEN 3
      WHEN 'Sad' THEN 2
      WHEN 'Angry' THEN 1
      ELSE 0
    END::smallint as mood_score,
    de.step_count
  FROM public.daily_entries de
  WHERE de.user_id = p_user_id
    AND de.date >= (CURRENT_DATE - INTERVAL '6 days')
  ORDER BY de.date;
END;
$$ LANGUAGE plpgsql;
